# Generated by Django 4.1.4 on 2023-01-23 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_news_newscategory_newsimage_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='publication/', verbose_name='Cover Image (270x347)')),
                ('file', models.FileField(blank=True, upload_to='publication/')),
                ('link', models.CharField(blank=True, max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='photo',
            field=models.ImageField(upload_to='group/', verbose_name='Photo (270x130)'),
        ),
    ]
