# Generated by Django 4.1.4 on 2023-01-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_counter_option4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='member/', verbose_name='Image (357x355)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='menuname',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(upload_to='slider/', verbose_name='Image (1920x780)'),
        ),
    ]
